SELECT
    car.CAR_ID,
    car.CAR_TYPE,
    (30 * car.DAILY_FEE * (100 - discount.DISCOUNT_RATE) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR car
    , CAR_RENTAL_COMPANY_DISCOUNT_PLAN discount
WHERE car.CAR_ID NOT IN (
    SELECT
        CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE NOT (END_DATE < DATE '2022-11-01' OR DATE '2022-12-01' <= START_DATE)
)
    AND car.CAR_TYPE IN ('SUV', '세단')
    AND car.CAR_TYPE = discount.CAR_TYPE
    AND discount.DURATION_TYPE LIKE '30일 이상'
    AND (30 * car.DAILY_FEE * (100 - discount.DISCOUNT_RATE) / 100) BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC