SELECT
    book.BOOK_ID,
    author.AUTHOR_NAME,
    TO_CHAR(book.PUBLISHED_DATE, 'YYYY-MM-DD') AS PUBLISHED_DATE
FROM BOOK book
    , AUTHOR author
WHERE book.CATEGORY = '경제'
    AND book.AUTHOR_ID = author.AUTHOR_ID
ORDER BY PUBLISHED_DATE